
services:
  - type: web
    name: site-assinatura
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: uma-chave-secreta-muito-forte
